cortex: cortex.cpp defs.h board.h board.cpp move.h move.cpp movegen.h movegen.cpp hash.h hash.cpp perft.h perft.cpp lookup_tables.h lookup_tables.cpp
	g++ cortex.cpp defs.h board.h board.cpp move.h move.cpp movegen.h movegen.cpp hash.h hash.cpp perft.h perft.cpp lookup_tables.h lookup_tables.cpp -o cortex.o -std=c++11 -O3 -Wall -Wextra -Wzero-as-null-pointer-constant -pedantic -pedantic-errors -Weffc++ -Wswitch-default -Wmissing-include-dirs -Wunreachable-code -Wfloat-equal

clean:
	rm cortex
