cortex: cortex.cc defs.h board.h board.cc move.h move.cc movegen.h movegen.cc search.h search.cc evaluate.h evaluate.cc hash.h hash.cc hash_table.h hash_table.cc chronos.h chronos.cc uci.h uci.cc misc.h misc.cc lookup_tables.h lookup_tables.cc perft.h perft.cc
	g++ cortex.cc defs.h board.h board.cc move.h move.cc movegen.h movegen.cc search.h search.cc evaluate.h evaluate.cc hash.h hash.cc hash_table.h hash_table.cc chronos.h chronos.cc uci.h uci.cc misc.h misc.cc lookup_tables.h lookup_tables.cc perft.h perft.cc -o cortex.o -std=c++11 -O3 -Wall -Wextra -Wzero-as-null-pointer-constant -pedantic -pedantic-errors -Weffc++ -Wswitch-default -Wmissing-include-dirs -Wunreachable-code -Wfloat-equal

clean:
	rm cortex
